name: Gradle Publish

on:
  push:
    branches: ['release']
  pull_request:
    branches: ['release']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: gradle
    
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      
      - name: Capture Artefacts
        uses: actions/upload-artifact@v3
        with:
          name: Jars
          path: build/libs/

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.ref_number }}
          release_name: Release v${{ github.ref_number }}

      - name: Added Artefacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.output.upload_url }}
          asset_path: build/libs/Silitics-${{ github.ref_number }}.jar
          asset_name: Silitics-${{ github.ref_number }}.jar
          asset_content_type: application/java-archive
