name: Gradle Publish

on:
  push:
    tags: ["v*"]
    branches: ["master"]
  pull_request:
    tags: ["v*"]
    branches: ["master"]

jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "temurin"
          cache: gradle
    
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      
      - name: Capture Artefacts
        uses: actions/upload-artifact@v3
        with:
          name: Artefacts
          path: build/libs/

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
