name: Gradle Build and Publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download JDK 1.8
        uses: actions/setup-java@3
        with:
          java-version: 8
          distribution: temurin
          cache: gradle
    
      - name: Build with Gradle
        uses: gradle/gradle-build-action@2
        with:
          arguments: build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    steps: 
    - uses: actions/checkout@v3
    - name: Capture Artefacts
      uses: actions/upload-artefact@v3
      with:
        name: Silitics.jar
        path: build/libs/*