name: Publishing

on:
  push:
    tags: 
      - 'v*.*.*'
  #release:
  #  types: [published]

jobs:
  build:
    name: Build And publish
    runs-on: ubuntu-latest
    steps:
      - name: Export Tag & Version Number to Environment
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      
      - name: Capture Artefacts
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/
          name: Jars

      - name: Create Release
        id: release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.TAG }}
          release_name: Release ${{ env.TAG }}

      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ step.release.outputs.upload_url }}
          asset_path: build/libs/Silitics-${{ env.VERSION }}.jar
          asset_name: Silitics-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
