name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Export Tag & Version Number to Environment
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      
      - name: Setup JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: gradle

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      
      - name: Capture Artefacts
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/
          name: Jars

      - name: Prepare artifact metadata
        id: prepare_artifact_metadata
        run: |
          echo ::set-output name=ARTIFACT_PATH::build/libs/Silitics-${VERSION}.jar
          echo ::set-output name=ARTIFACT_NAME::Silitics-${VERSION}.jar
      
      - name: Upload Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/Silitics-${{ env.VERSION }}.jar
          asset_name: Silitics-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive

